version: '3'

services:
  server:
    container_name: amiddocs_server
    build: .
    image: amiddocs_server_image
    ports:
      - "10101:10101"
    volumes:
      - ./files:/files
    depends_on:
      - migrate
    environment:
      - MODE=docker
  db:
    container_name: amiddocs_db
    image: postgres:alpine3.17
    volumes:
      - ./.tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: amiddoc_go
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "54333:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
  migrate:
    container_name: amiddocs_migrate
    image: migrate/migrate:v4.15.2
    volumes:
        - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:admin@db:5432/amiddoc_go?sslmode=disable", "up"]
    depends_on:
      - db
  
