
server:
  host: 0.0.0.0
  port: 10101
  url: http://0.0.0.0:10101
  client_token: 9eba7999-854b-46a2-b118-1cf5b99ec5fc
postgres:
  local_url: postgres://postgres:admin@localhost:54333/amiddoc_go
  docker_url: postgres://postgres:admin@db:5432/amiddoc_go
jwt:
  name: token
  pempath: "./config/private.pem"
  access_token_time: 86400
  refresh_token_time: 2592000


