// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/departments/create": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "enabled auto check unique name and shortName values",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "departments"
                ],
                "summary": "Create department",
                "parameters": [
                    {
                        "description": "department dto",
                        "name": "department",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/depmodel.CreateDepartmentDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/depmodel.DepartmentDTO"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/departments/get-all": {
            "get": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "departments"
                ],
                "summary": "Get All Departmnets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/depmodel.DepartmentDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/departments/get-all-types": {
            "get": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "get all departments with them doc types",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "departments"
                ],
                "summary": "GetAllDepartmentsWithTypes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/depmodel.DepartmentTypes"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/departments/get-by-id": {
            "get": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "return department dto by id in param",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "departments"
                ],
                "summary": "Get Department By own ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/depmodel.DepartmentDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/document-templates/get": {
            "get": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "returns raw file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "document-templates"
                ],
                "summary": "get template document",
                "parameters": [
                    {
                        "enum": [
                            "STUDY_DOCUMENT_BUDGET",
                            "STUDY_DOCUMENT_NO_BUDGET"
                        ],
                        "type": "string",
                        "description": "document type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "department id",
                        "name": "departmentId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/document-templates/upload": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "load or update template in files",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "document-templates"
                ],
                "summary": "load document template",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department id",
                        "name": "depId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "STUDY_DOCUMENT_BUDGET",
                            "STUDY_DOCUMENT_NO_BUDGET"
                        ],
                        "type": "string",
                        "description": "document type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "document binary (.docx file)",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/create": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "create group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "CreateGroup",
                "parameters": [
                    {
                        "description": "group dto",
                        "name": "groups",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/groupmodel.GroupDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/groupmodel.GroupDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/get-by-id": {
            "get": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "Get GroupDTO by Id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "Get Group By Id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "group id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/groupmodel.GroupDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/requests/by-department-id": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "get all requests with send status by dep id from query requires secretary access",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "DepartmentRequests",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department id",
                        "name": "depId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/reqmodel.RequestViewDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/requests/cancel": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "\"Delete request if status == SEND\"",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "Cancel request by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "request id",
                        "name": "requestId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/requests/generate-document": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "returns document from request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "GenerateDocumentFromRequest",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "request id",
                        "name": "reqId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/requests/history-by-department-id": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "get all requests with done status by dep id from query requires secretary access",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "HistoryDepartentRequests",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "department id",
                        "name": "depId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/reqmodel.RequestViewDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/requests/my-requests": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "get user requests by id from jwt token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "UserRequests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/reqmodel.RequestDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/requests/send": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "\"Send request to generate document\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "Send request",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reqmodel.CreateRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/reqmodel.RequestDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/requests/set-done": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "set request status done by req id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "requests"
                ],
                "summary": "SetRequestStatusDone",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "request id",
                        "name": "reqId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/reqmodel.RequestViewDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/students/create": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "create student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Create Student",
                "parameters": [
                    {
                        "description": "create student dto",
                        "name": "student",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/studentmodel.CreateStudentDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/studentmodel.StudentDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/students/get-by-id": {
            "get": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "get student by id from query param",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "GetStudentByID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "student id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/studentmodel.StudentDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/students/info": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "get student by id from query param",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "GetStudentByID",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/studentmodel.StudentDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/all": {
            "get": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "get all users from database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get All Users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/usermodel.UserDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/get-by-id": {
            "get": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "return user by id from path",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Return User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "get user by id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usermodel.UserDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/info": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "return user by id from path",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Return User",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usermodel.UserDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "login by login and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "login form",
                        "name": "loginForm",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usermodel.LoginForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenmodel.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/refresh-token": {
            "post": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "refresh token by old token and user id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "refresh token",
                "parameters": [
                    {
                        "description": "refresh dto with user id and old token",
                        "name": "refreshdto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rtokenmodel.RefreshDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tokenmodel.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    },
                    {
                        "Token": []
                    }
                ],
                "description": "register user, require createUserModel, email should be unique",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "RegisterUser",
                "parameters": [
                    {
                        "description": "create user dto",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usermodel.CreateUserDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/usermodel.UserDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/amiderrors.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "amiderrors.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "depmodel.CreateDepartmentDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "shortName": {
                    "type": "string"
                }
            }
        },
        "depmodel.DepartmentDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "depmodel.DepartmentTypes": {
            "type": "object",
            "properties": {
                "department": {
                    "$ref": "#/definitions/depmodel.DepartmentDTO"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/doctypefields.DocumentType"
                    }
                }
            }
        },
        "doctypefields.DocumentType": {
            "type": "string",
            "enum": [
                "STUDY_DOCUMENT_BUDGET",
                "STUDY_DOCUMENT_NO_BUDGET"
            ],
            "x-enum-varnames": [
                "STUDY_DOCUMENT_BUDGET",
                "STUDY_DOCUMENT_NO_BUDGET"
            ]
        },
        "doctypemodel.DocumentTypeDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "refresh_time": {
                    "type": "integer"
                },
                "role": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/userfields.Role"
                    }
                },
                "type": {
                    "$ref": "#/definitions/doctypefields.DocumentType"
                }
            }
        },
        "groupfields.EducationForm": {
            "type": "string",
            "enum": [
                "FULL_TIME",
                "EXTRAMURAL"
            ],
            "x-enum-varnames": [
                "FULL_TIME",
                "EXTRAMURAL"
            ]
        },
        "groupmodel.GroupDTO": {
            "type": "object",
            "properties": {
                "educationFinishDate": {
                    "type": "string"
                },
                "educationForm": {
                    "$ref": "#/definitions/groupfields.EducationForm"
                },
                "educationStartDate": {
                    "type": "string"
                },
                "educationYear": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "isBudget": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "studyDepartmentId": {
                    "type": "integer"
                }
            }
        },
        "reqfields.Status": {
            "type": "string",
            "enum": [
                "SEND",
                "IN_PROGRESS",
                "DONE"
            ],
            "x-enum-varnames": [
                "SEND",
                "IN_PROGRESS",
                "DONE"
            ]
        },
        "reqmodel.CreateRequestDTO": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "departmentId": {
                    "type": "integer"
                },
                "documentType": {
                    "$ref": "#/definitions/doctypefields.DocumentType"
                }
            }
        },
        "reqmodel.RequestDTO": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "departmentId": {
                    "type": "integer"
                },
                "documentType": {
                    "$ref": "#/definitions/doctypemodel.DocumentTypeDTO"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/reqfields.Status"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "reqmodel.RequestViewDTO": {
            "type": "object",
            "properties": {
                "documentCount": {
                    "type": "integer"
                },
                "documentType": {
                    "$ref": "#/definitions/doctypefields.DocumentType"
                },
                "fio": {
                    "$ref": "#/definitions/reqmodel.fio"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/reqfields.Status"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "reqmodel.fio": {
            "type": "object",
            "properties": {
                "fatherName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "rtokenmodel.RefreshDTO": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "stdocmodel.StudentDocumentDTO": {
            "type": "object",
            "properties": {
                "docNumber": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "orderDate": {
                    "type": "string"
                },
                "orderNumber": {
                    "type": "string"
                },
                "studentId": {
                    "type": "integer"
                },
                "studyStartDate": {
                    "type": "string"
                }
            }
        },
        "studentmodel.CreateStudentDTO": {
            "type": "object",
            "properties": {
                "docNumber": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fatherName": {
                    "type": "string"
                },
                "groupName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "orderDate": {
                    "type": "string"
                },
                "orderNumber": {
                    "type": "string"
                },
                "studyStartDate": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "studentmodel.StudentDTO": {
            "type": "object",
            "properties": {
                "department": {
                    "$ref": "#/definitions/depmodel.DepartmentDTO"
                },
                "document": {
                    "$ref": "#/definitions/stdocmodel.StudentDocumentDTO"
                },
                "group": {
                    "$ref": "#/definitions/groupmodel.GroupDTO"
                },
                "id": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/usermodel.UserDTO"
                }
            }
        },
        "tokenmodel.TokenResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/userfields.Role"
                    }
                }
            }
        },
        "userfields.Role": {
            "type": "string",
            "enum": [
                "STUDENT",
                "ADMIN",
                "SECRETARY"
            ],
            "x-enum-varnames": [
                "STUDENT",
                "ADMIN",
                "SECRETARY"
            ]
        },
        "usermodel.CreateUserDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fatherName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/userfields.Role"
                    }
                },
                "surname": {
                    "type": "string"
                }
            }
        },
        "usermodel.LoginForm": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "usermodel.UserDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fatherName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/userfields.Role"
                    }
                },
                "surname": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Bearer Token Auth",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "Token": {
            "description": "Client Token auth",
            "type": "apiKey",
            "name": "Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "AMIDDOCS OFFICIAL SWAGGER",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
